name: CI Backend

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/ci-backend.yml"
  pull_request:
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: pnpm install

      - name: Build backend
        run: pnpm build

      # Opcional: adicionar testes
      - name: Run tests
        run: pnpm test
        continue-on-error: true
